#!/usr/bin/env zsh

# Postino install script

if ! [ -r src/postino ]; then
    echo "Error: this script should be run from inside a postino software distribution"
    exit 1
fi


WORKDIR=$HOME/.postino
MAILDIR=$HOME/Mail

if [ $1 ]; then WORKDIR=$1; fi
# make sure the directory is private
mkdir -p $WORKDIR
chmod 700 $WORKDIR

source src/postino

notice "Installing Postino in $WORKDIR"

if [ $? != 0 ]; then
    error "Postino directory $WORKDIR is not private, set its permissions to 700"
    error "Refusing to proceed."
    exit 1
fi

# make sure we have a temp and cache dir
mkdir -p $WORKDIR/tmp $WORKDIR/cache
chmod 700 $WORKDIR/tmp $WORKDIR/cache

if ! [ -r $MAILDIR/Configuration.txt ]; then
    cat <<EOF > $MAILDIR/Configuration.txt
# MAIL USER (the left and right parts of an email)
NAME=user
# @
DOMAIN=gmail.com

# SMTP (SEND)
SMTP_ADDRESS=smtp.gmail.com
SMTP_LOGIN=\${NAME}@\${DOMAIN}
SMTP_PASSWORD=my_secret_pass
SMTP_PORT=25
# SMTP_CERTIFICATE=gmail.pem

# IMAP (RECEIVE)
IMAP_ADDRESS=imap.gmail.com
IMAP_LOGIN=\${NAME}@\${DOMAIN}
IMAP_PASSWORD=my_secret_pass
IMAP_PORT=443

# LOCAL FILES
# to change the location of this directory,
# export POSTINO_DIR as env var
# the defaults below should be ok, they place
# mutt, procmail, mstmp and other confs in ~/.postino

MAILDIRS=$HOME/Mail
MUTTDIR=$WORKDIR/.mutt
PROCMAILDIR=$WORKDIR/.procmail
CERTIFICATES=$HOME/.ssl/certs

# directory of the sieve filter
# REMOTE_FILTER=/var/mail/...
EOF
    act "Default configuration created"
else
    error "Existing $MAILDIR/Configuration.txt skipped"
fi

# source the default configuration
source $MAILDIR/Configuration.txt

if ! [ -r $MAILDIR/Filters.txt ]; then
    cat <<EOF > $MAILDIR/Filters.txt
# Example filter configuration for Postino

# accepted email addresses
to	  jaromil@dyne.org	save	priv
to	  jaromil@kyuzz.org	save	priv
to	  jaromil@enemy.org	save	priv
to	  jaromil@montevideo.nl	save	priv

# mailinglist filters, in order of importance
to	  crypto@lists.dyne	save	dyne.crypto
to	  dynebolic		save	dyne.dynebolic
to	  freej			save	dyne.freej
to	  frei0r-devel		save	dyne.frei0r
to	  taccuino		save	ml.freaknet
to	  deadpoets		save	ml.freaknet
to	  linux-libre		save	gnu.linux-libre
to	  foundations@lists	save	gnu.foundations
to	  debian-mentors	save	debian.mentors
to	  debian-blends		save	debian.blends
to	  freedombox-discuss	save	debian.freedombox

# other filters for web 2.0 services
from      identi.ca	        save	web.identica
from      Twitter		save	web.twitter
from      linkedin		save	web.linkedin
from      googlealerts		save	web.google
from      facebook		save	web.facebook
from      FriendFeed		save	web.friendfeed
from      academia.edu		save	web.academia

EOF
    act "Default filters created"
else
    error "Existing configuration $MAILDIR/Filters.txt skipped"
fi

source $MAILDIR/Configuration.txt

# make sure maildirs where to put mails exist
mkdir -p $MAILDIRS
chmod 700 $MAILDIRS
maildirmake $MAILDIRS/known
maildirmake $MAILDIRS/sent
maildirmake $MAILDIRS/priv
maildirmake $MAILDIRS/postponed
maildirmake $MAILDIRS/unsorted

if ! [ -r $MUTTDIR ]; then
    mkdir -p $MUTTDIR
    cat<<EOF > $MUTTDIR/rc
# mutt config generated by postino
# don't edit, change Mail/Configuration.txt instead
unset use_domain
set hostname = $DOMAIN
set realname = $NAME
set folder = $MAILDIRS
set spoolfile = $MAILDIRS/known/
set record = $MAILDIRS/sent/
set postponed= $MAILDIRS/postponed/
set tmpdir = $WORKDIR/tmp
set query_command = "postino query '%s'"
set sendmail = "postino queue"
set header_cache= $MUTTDIR/cache
set maildir_header_cache_verify=no
set editor = "$EDITOR"
set mailcap_path = "$WORKDIR/mailcap"

# mailboxes in order of priority
source $MUTTDIR/mboxes
# user tweaked configuration
source $MUTTDIR/general
## end of generated muttrc
##########################

EOF
    cp -f share/mutt/* $MUTTDIR/
    touch $MUTTDIR/mboxes
    ln -sf $MUTTDIR/rc $HOME/.muttrc
    if [ $? != 0 ]; then
	error "Error setting Postino to handle Mutt's default configuration"
	error "Set symlink manually: $HOME/.muttrc -> $MUTTDIR/rc"
    fi
    act "Default mutt configuration created"
else
    error "Existing configuration for Mutt skipped"
fi

# procmail is entirely generated
# so overwriting it won't hurt
act "Installing procmail scripts"
mkdir -p $PROCMAILDIR
cp -a share/procmail/* $PROCMAILDIR

case `uname -s` in
	Darwin)
		mkdir -p $WORKDIR/bin
		if [ -r build/osx ]; then
			cp -a build/osx/* $WORKDIR/bin
		fi
		touch $HOME/.profile
		cat $HOME/.profile | grep '^# Postino' > /dev/null
		if [ $? != 0 ]; then
			cat <<EOF >> $HOME/.profile
# Postino Installer addition on `date`
export PATH=$WORKDIR/bin:\$PATH
# Finished adapting your PATH
EOF
		fi
	;;
	Linux)
		# TODO
	;;
esac
	
notice "Installation completed, now edit your personal settings:"
act "$MAILDIR/Configuration.conf"
if [ `uname -s` = Darwin ]; then
	open /Applications/TextEdit.app $MAILDIR/Configuration.txt
fi
