#!/usr/bin/env zsh
#
# Jaro Mail, your humble and faithful electronic postman
#
# a tool to easily and privately handle your e-mail communication
#
# Copyleft (C) 2010-2012 Denis Roio <jaromil@dyne.org>
#
# This source  code is free  software; you can redistribute  it and/or
# modify it under the terms of  the GNU Public License as published by
# the Free  Software Foundation; either  version 3 of the  License, or
# (at your option) any later version.
#
# This source code is distributed in  the hope that it will be useful,
# but  WITHOUT ANY  WARRANTY;  without even  the  implied warranty  of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# Please refer to the GNU Public License for more details.
#
# You should have received a copy of the GNU Public License along with
# this source code; if not, write to:
# Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.



###################
# Jaro Brother DB
create_addressbook() {
    func "create addressbook"
    { test -r "$WORKDIR/addressbook" } && {
	error "Addressbook already exists: $WORKDIR/addressbook"
	return 1
    }
    cat <<EOF | ${SQL} -batch $WORKDIR/addressbook
CREATE TABLE whitelist
(
  email   text collate nocase unique,
  name    text collate nocase
);
CREATE TABLE blacklist
(
  email   text collate nocase unique,
  name    text collate nocase
);
EOF
    { test $? != 0 } && {
	error "Error creating addressbook database."
	return 1 }
    # make sure is private
    chmod 600 $WORKDIR/addressbook
    return 0
}
insert_address() {
    func "insert address: $1, $2"
    cat <<EOF | ${SQL} -batch ${addressbook} 2> /dev/null
INSERT INTO $list (email, name)
VALUES ("${1}", "${2}");
EOF
    { test $? != 0 } && {
	func "address already present in $list"
	return 1
    }
    return $0
}

# update_name() {
#     func "update address: $1, $2"
#     cat <<EOF | ${SQL} -batch $WORKDIR/addressbook 2> /dev/null
# UPDATE $list SET name="${2}" WHERE email LIKE "${1}";
# EOF
#     { test $? != 0 } && {
# 	func "address not found or error occurred" }
# }

remove_address() {
    func "remove address <$1> from $list"
    cat <<EOF | ${SQL} -batch ${addressbook}
DELETE FROM $list
WHERE email IS "${1}";
EOF
    { test $? != 0 } && {
	func "address not found or error occurred" }
}
search_name() {
    func "search_name from $list like $1"
	cat <<EOF | ${SQL} -column -batch ${addressbook}
.width 64 128
SELECT * FROM $list
WHERE name LIKE "%${1}%";
EOF
}
search_email() {
    func "search email from $list is $1"
    cat <<EOF | ${SQL} -column -batch ${addressbook}
SELECT rowid FROM $list
WHERE email IS "${1}";
EOF
}

complete() {
    func "complete from $list: ${PARAM[1]}"

    act "Searching for \"${PARAM[1]}\" in $list"

    matches="${matches}\n`search_name ${PARAM[1]}`"

    # mutt query requires something like this
    print "jaro: $((`print $matches | wc -l` -1)) matches"
    print "$matches" | awk '
{ printf "%s\t", $1
  for(i=2;i<=NF;i++) {
    sub("<","",$i)
    sub(">","",$i)
    if($i!=$1) printf "%s ", $i
  }
  printf "\n" }'
}
isknown() {
    func "is known in $list: (string from stdin)"

    head="`${WORKDIR}/bin/fetchaddr -x From: -a`"


    email="${head[(ws:,:)1]}"

    exitcode=1

    lookup="`search_email ${email}`"

    { test "$lookup" != "" } && { exitcode=0 }

    act "Email <$email> found in $list with id $lookup"
}

learn() {
    func "learn ${PARAM[1]} from mail in stdin"

    what=sender
    { test -z ${PARAM[1]} } || { what=${PARAM[1]} }
    case ${PARAM[1]} in
	sender) # simple: one address only on From:
	    head="`cat | ${WORKDIR}/bin/fetchaddr -x From: -a`"
	    email="${head[(ws:,:)1]}"
	    name="${head[(ws:,:)2]}"
	    insert_address "$email" "$name"
	    return 0
	    ;;
	recipient) # complex: more addresses in To: and Cc:
	    head="`cat | ${WORKDIR}/bin/fetchaddr -x To: -a`"
	    for h in ${(f)head}; do
		email="${h[(ws:,:)1]}"
		name="${h[(ws:,:)2]}"
		insert_address "$email" "$name"
	    done
	    head="`cat | ${WORKDIR}/bin/fetchaddr -x Cc: -a`"
	    for h in ${(f)head}; do
		email="${h[(ws:,:)1]}"
		name="${h[(ws:,:)2]}"
		insert_address "$email" "$name"
	    done
	    return 0
	    ;;
	*)
	    error "Unknown learning function: $what" ;;
    esac
    return 1
}

forget() {
    func "forget sender from mail in stdin"

    act "Expecting mail from stdin pipe"
    head="`${WORKDIR}/bin/fetchaddr -x From:`"

    # forget the email part of the parsed head
    remove_address "${head[(ws:,:)1]}"
}
list_addresses() {
    func "list addresses in ${PARAM[1]}"

    { test ${PARAM[1]} } && { list=${PARAM[1]} }

    act "Listing all contents for $list"
    cat <<EOF | ${SQL} -column -header -batch ${addressbook}
.width 32 40
SELECT * FROM $list;
EOF
}

# import an addressbook, autodetect its type
import_addressbook() {
    notice "Importing addressbook"
    if [ "${PARAM[1]}" != "" ]; then
	func "file specified: ${PARAM[1]}"
	# a file was given as argument
	import_vcard ${PARAM[2]}
    else
	# no file as parameter
	{ test "$OS" = "MAC" } && { import_macosx }
    fi
}

    
# import addressbook from Mac/OSX
import_macosx() {
    act "system addressbook from Mac/OSX"
    { test "$OS" = "MAC" } || { error "Not running on Mac/OSX, operation aborted." }
    { command -v ABQuery > /dev/null } || {
	error "ABQuery not found, operation aborted." }

    tmp=$TMPDIR/abook.import_osx.$datestamp.$RANDOM
    newlock $tmp

    # import all the Mac addressbook
    ABQuery @ | awk '
{ printf "%s|", $1; for(i=2;i<=NF;i++) { printf "%s ", $i } }
' >> $tmp
    addresses=`cat $tmp`
    unlink $tmp

    lock ${addressbook}

    new=0; dupes=0;
    for a in ${(f)addresses}; do
	_email=`echo $a | cut -d'|' -f1`
	# remove from name all what is an email between brackets
	# crop (trim) all beginning and ending whitespaces from name
	_name=`echo $a | cut -d'|' -f2 | sed 's/<.*>//;s/^[ \t]*//;s/[ \t]*$//'`
	insert_address ${_email} ${_name}
	if [ $? = 0 ]; then new=$(( $new + 1 ))
	else dupes=$(( $dupes + 1 )); fi
    done

    unlock ${addressbook}

    notice "Operation completed"
    act "$new new addresses imported"
    act "$dupes duplicate addresses skipped"
    return 0
}
# import addresbook email from VCard
import_vcard() {
    act "import VCard from file: ${PARAM[1]}"

    { test -r "${PARAM[1]}" } || {
	error "File not found: ${PARAM[1]}"
	return 1
    }

    vcard=${PARAM[1]}
    head -n1 $vcard | grep '^BEGIN:VCARD' > /dev/null

    { test $? = 0 } || {
	error "File to import is not a VCard: $vcard"
	return 1
    }

    notice "Import in addressbook VCard ${vcard}"
    tmp=$TMPDIR/import.$datestamp.$RANDOM

    # parse the vcard and print a simple name and email list
    # each value on a single line, entry tuples followed by a #
    # we skip entries that don't have an email
    cat ${vcard} | awk '
BEGIN { newcard=0; c=0; name=""; email=""; }
/^BEGIN:VCARD/ { newcard=1 }
/^FN:/ { if(newcard = 1) name=$0 }
/^EMAIL/ { if(newcard = 1) email=$0 }
/^END:VCARD/ {
  if(newcard = 1) {
    newcard=0
    if(email != "") {
      c+=1
      print name
      print email
      print "# " c 
    }
    email=""
    next
  }
}
' | cut -d: -f2  > $tmp

    # now parse the temporary list of name and emails
    # made of name, email and a hash for each, newline separated
    addresses=`cat $tmp`
    ${=rm} $tmp

    lock ${addressbook}

    newa=1; _name=""; _email=""
    for a in ${(f)addresses}; do
	{ test "${a[1]}" = "#" } && {
	    newa=1; # its the end of the entry
	    # check if we have this email already
	    foundemail=`search_email "${_email}"`
	    { test "$foundemail" = "" } && {
		insert_address "${_email}" "${_name}"
		act "${a} ${_name} <${_email}>"
	    }

	    continue }
	{ test $newa -eq 1 } && {
	    # (V) makes special chars visible, we need to remove them..
	    _name=`echo ${(V)a} | cut -d^ -f1`; newa=0; continue }
	{ test $newa -eq 0 } && { _email=`echo ${(V)a} | cut -d^ -f1` }
    done

    unlock ${addressbook}

    notice "Done importing addresses"
}

# export addressbook to vcard
export_vcard() {

    act "Export addressbook into vCard $WORKDIR/addressbook.vcf"
    tmp=$TMPDIR/export.$datestamp.$RANDOM

    lock ${addressbook}

    cat <<EOF | ${SQL} -column -header -batch ${addressbook} \
	| grep -v '^email' > $tmp
.width 40 100
.mode list
.separator '|'
SELECT email, name FROM $list;
EOF

    unlock ${addressbook}

    addresses=`cat $tmp`
    ${=rm} $tmp

    rm -f $WORKDIR/addressbook.vcf
    touch $WORKDIR/addressbook.vcf
    for a in ${(f)addresses}; do
	_email=`echo $a | cut -d'|' -f1`
	# remove from name all what is an email between brackets
	# crop (trim) all beginning and ending whitespaces from name
	_name=`echo $a | cut -d'|' -f2 | sed 's/<.*>//;s/^[ \t]*//;s/[ \t]*$//'`
	{ test "${_email}" != "" } && {
	    cat <<EOF >> $WORKDIR/addressbook.vcf
BEGIN:VCARD
VERSION:3.0
FN:${_name}
EMAIL;TYPE=HOME:${_email// /}
END:VCARD
EOF
	}
    done

}

edit_abook() {
    # take argument even without option -l
    { test -z ${PARAM[1]} } || { list=${PARAM[1]} }

    # check if abook binary is found
    { command -v abook > /dev/null } || {
	error "ABook not found, operation aborted."
	return 1
    }

    lock ${addressbook}

    act "Editing addressbook $list"
    tmp=$TMPDIR/abook.$datestamp.$RANDOM
    newlock $tmp

    tmpread=$TMPDIR/abook.read.$datestamp.$RANDOM
    newlock $tmpread
    cp ${addressbook} $tmpread
    cat <<EOF | ${SQL} -column -header -batch $tmpread \
	| grep -v '^email' > $tmp
.width 40 100
.mode list
.separator '|'
SELECT email, name FROM $list;
EOF

    { test "$OS" = "MAC" } && {
    }
    addresses=`cat $tmp`
    rm -f $tmp

    unlink $tmpread

    cat <<EOF > $tmp
# abook addressbook file

[format]
program=jaromail
version=1.0

EOF
    c=0
    for a in ${(f)addresses}; do
	_email=`echo $a | cut -d'|' -f1`
	# remove from name all what is an email between brackets
	# crop (trim) all beginning and ending whitespaces from name
	_name=`echo $a | cut -d'|' -f2 | sed 's/<.*>//;s/^[ \t]*//;s/[ \t]*$//'`
	{ test "${_email}" != "" } && {
	    cat <<EOF >> $tmp
[${c}]
name=${_name}
email=${_email}

EOF
	    c=$(( $c + 1 ))
	}
    done

    # generate abook configuration
    abookrc=$TMPDIR/abookrc.$datestamp.$RANDOM
    cat <<EOF > $abookrc
set autosave=true
set emailpos=35
set extra_column=-1
set mutt_command=jaro
set sort_field=name
EOF

    abook --config $abookrc --datafile $tmp
    # remove config and backup turd
    ${=rm} ${tmp}~
    ${=rm} ${abookrc}

    tmpspruce=$TMPDIR/abook.spruce.$datestamp.$RANDOM
    newlock $tmpspruce

    abook --convert --infile $tmp \
	--outformat spruce | awk '
BEGIN { c=0; name=""; email=""; }
/^#/ { if(email != "") {
          c+=1
          print name
          print email
          print "# " c
       }
       email=""
       next
     }
/^Name:/ { name=$0 }
/^Email:/ { email=$0 }
' > $tmpspruce
    addresses=`cat $tmpspruce`
    unlink $tmpspruce

    rm -f $tmp

    # move addressbook to old
    act "Updating the addressbook database"
    cat <<EOF > $tmp
DROP TABLE $list;
CREATE TABLE $list
(
  email   text collate nocase unique,
  name    text collate nocase
);

EOF

    newa=1; _name=""; _email=""
    for a in ${(f)addresses}; do

	{ test "${a[1]}" = "#" } && {
	    newa=1; #its the end of the entry
	    print "INSERT INTO $list (email, name) VALUES (\"${_email}\", \"${_name}\");" >> $tmp
	    continue }

	{ test $newa -eq 1 } && {
	    _name=`echo ${a} | cut -d: -f2`; newa=0; continue }
	{ test $newa -eq 0 } && { _email=`echo ${a// /} | cut -d: -f2` }

    done
    func "Inserting the updated addressbook"
    tmpwrite=$TMPDIR/abook.write.$datestamp.$RANDOM
    newlock $tmpwrite
    cp ${addressbook} $tmpwrite
    cat $tmp | ${SQL} -batch $tmpwrite 2> /dev/null
    unlink $tmp
    cp $tmpwrite ${addressbook}
    unlock ${addressbook}
    unlink $tmpwrite
    notice "Addressbook updated"
}
###################
