#!/usr/bin/env zsh

cmd_compose() {
    stdin_compose ${option_params}
    exitcode=$?
}

cmd_queue() {
    stdin_queue ${option_params}
    exitcode=$?
}

cmd_fetch() {
    fetch ${option_params} && \
        update_filters && \
        filter_maildir incoming && \
        update_notmuch
}

cmd_send() {
    send ${option_params}
    exitcode=$?
}

cmd_peek() {
    peek ${option_params}
    exitcode=$?
}

cmd_remember() {
    deliver remember
    exitcode=$?
}

cmd_replay() {
    replay ${option_params}
    exitcode=$?
}

cmd_init() {
    init_inbox
    nm_setup
    read_account
    mblaze_setup
    if [[ -r "$MAILDIRS/.envrc" ]]; then
        warning "Cannot overwrite direnv conf: $MAILDIRS/.envrc"
        warning "Delete it manually if desired."
    else
        cat <<EOF > "$MAILDIRS/.envrc"
export JAROMAILDIR=$MAILDIRS
export JAROWORKDIR=/usr/local/share/jaromail
export NOTMUCH_CONFIG=$MAILDIRS/notmuch-config
export MBLAZE=$MAILDIRS/.mblaze
EOF
    fi
    command -v direnv >/dev/null || {
        direnv allow
        act "direnv configuration in .envrc"
    }
    notice "Initialization completed in $MAILDIRS"
}

cmd_update() {
    [[ "$option_params" = "" ]] || {
        for p in $option_params; do
            [[ "$p" = "." ]] && p=$PWD
            [[ -d $p ]] && MAILDIRS=$p
        done
    }
    read_account
    mblaze_setup
    update_filters
    update_sieve
    update_notmuch
    notice "Initialization completed in $MAILDIRS"
}

cmd_sieve() {
    read_account
    mblaze_setup
    update_filters
    update_sieve
    notice "Sieve filters updated in $MAILDIRS"
}

cmd_help() {
    usage
}

cmd_index() {
    nm_setup
    nm_index
    exitcode=$?
}

cmd_search() {
    search ${option_params}
    [[ $DRYRUN = 1 ]] || {
        for i in ${search_results=}; do
            print - "$i"
        done
    } | save_replay $subcommand
}
