#!/usr/bin/env zsh
#
# Jaro Mail, your humble and faithful electronic postman
#
# a tool to easily and privately handle your e-mail communication
#
# Copyleft (C) 2010-2015 Denis Roio <jaromil@dyne.org>
#
# This source  code is free  software; you can redistribute  it and/or
# modify it under the terms of  the GNU Public License as published by
# the Free  Software Foundation; either  version 3 of the  License, or
# (at your option) any later version.
#
# This source code is distributed in  the hope that it will be useful,
# but  WITHOUT ANY  WARRANTY;  without even  the  implied warranty  of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# Please refer to the GNU Public License for more details.
#
# You should have received a copy of the GNU Public License along with
# this source code; if not, write to:
# Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

#######################
## Search into maildirs
# using notmuch


# internal use
nm() {
    fn "notmuch $*"

    [[ -r "$MAILDIRS"/notmuch-config ]] || nm_setup
    notmuch --config="$MAILDIRS"/notmuch-config $*
    [[ $? = 0 ]] || {
        error "Notmuch error on command: ${@}"
        func "Returning status to caller: $_res"
    }
    return $_res
}

nm_setup() {
    fn nm_setup

    nm_conf="$MAILDIRS"/notmuch-config

    # setup the default tags for all new messages
    deftags="$1"

    act "notmuch setup $deftags"
    
    # read if there are other email aliases configured
    [[ -r "$MAILDIRS"/Aliases.txt ]] && {
        other_email="other_email"
        _aliases=`grep -v '^#' "$MAILDIRS"/Aliases.txt`
        _sep=\=
        for i in ${(f)_aliases}; do
            other_email+="${_sep}${i}"
            _sep=";"
        done
    }

    rm -f "$nm_conf"
    cat <<EOF > "$nm_conf"
[database]
path=$MAILDIRS

[new]
tags=$deftags
ignore=tmp;cache;logs;outbox;incoming;zz.social;zz.bounces;zz.blacklist;zz.spam;Spam;Accounts;Groups;.mutt;webnomad;Aliases.txt;Filters;Manual.pdf;Mutt.txt;whitelist.abook;blacklist.abook;Applications.txt;Filters.sieve;Filters.txt;.password-store;.envrc;.host;.last;.tty;.uid;alot-config;notmuch-config;bind-hooks;sieve-update;.mblaze

[maildir]
synchronize_flags=true
EOF
    [[ "$name" = "" ]] && read_account

    cat <<EOF >> "$nm_conf"
[user]
name=$name
primary_email=$email
$other_email
EOF

	notmuch --config "$nm_conf" new
}

nm_index() {
    fn nm_index

    # init the environment
    read_account
    notice "Indexing all mail archive"
    act "please wait, this may take a while..."
    lock "$MAILDIRS"/cache/notmuch

    nm new
    nm tag +inbox +priv -unsorted folder:known
    nm tag +inbox +priv -unsorted folder:sent
    nm tag -inbox +priv -unsorted folder:priv
    nm tag -inbox -priv +unsorted folder:unsorted
    act "compressing database"
    nm compact
    unlock "$MAILDIRS"/cache/notmuch
    notice "Indexing completed"
}

update_notmuch() {
    fn update_notmuch

    isfound notmuch && [[ -r $MAILDIRS/.notmuch/xapian ]] && {
        notice "Updating notmuch indexes"
        nm_setup
        nm new 2>&1 | grep -v '^Note: Ignoring'
    }
}

search() {
    fn search $*
    notice "Searching for ${#option_params} terms"
    # launch the search with notmuch

    nm search --output=files $*

    [[ $? = 0 ]] || {
        error "notmuch search failed with an error"
        return 1
    }
}

alot_setup() {
	fn alot_setup $*
	nm_setup
	act "alot setup configuration"
	other_email=`grep '^other_email' "${MAILDIRS}/notmuch-config"`
	name=`grep '^name=' "${MAILDIRS}/notmuch-config" | cut -d= -f2`
	email=`grep '^primary_email=' "${MAILDIRS}/notmuch-config" | cut -d= -f2`

    # setup alot to show results
    cat <<EOF > "$MAILDIRS"/alot-config

editor_cmd = jaro edit
edit_headers_whitelist = From,To,Cc,Subject
displayed_headers = From,To,Cc,Bcc,Subject
auto_remove_unread = True
honor_followup_to = True
hooksfile = $MAILDIRS/cache/alot/hooks.py
initial_command = search tag:inbox
prefer_plaintext = True
tabwidth = 4
user_agent = JaroMail <https://dyne.org/software/jaro-mail>

[bindings]
  i = search tag:inbox
  p = search tag:priv
  u = search tag:unsorted
  / = prompt 'search '
  l = prompt 'search '
  backspace = bclose

[accounts]
    [[$account]]
        realname = $name
        address = $email
        sendmail_command = jaro queue
        sent_box = maildir:///$MAILDIRS/sent
        $other_email
        [[[abook]]]
           type = shellcommand
           command = jaro -q search addr
           regexp = (?P<name>.+)\s*<(?P<email>.*.+?@.+?)>

[tags]
  [[inbox]]
    translated = ★
  [[priv]]
    translated = ⚡
  [[attachment]]
    translated = ⚓
  [[unsorted]]
    translated = ?
  [[flagged]]
    translated = ⚑
    normal = '','','light red','','light red',''
    focus = '','','light red','','light red',''
  [[unread]]
    translated = ☉
  [[replied]]
    translated = ⏎
  [[encrypted]]
    translated = ⚷
  [[signed]]
    translated = ✍
  [[filters]]
    translated = ⚙
  [[mailinglist]]
    translated = ☰
EOF

}

# run a search with notmuch and show results with alot
alot_search() {
    fn alot_search $*

    notice "Searching emails for: ${=option_params}"
	[[ -r "$MAILDIRS"/notmuch-config ]] || {
		error "notmuch configuration not found"
		error "run: jaro update"
		return 1
	}

    alot -r \
		-c "$MAILDIRS"/alot-config \
		-n "$MAILDIRS"/notmuch-config \
        search $*

    return $?
}

backup() {
    fn backup $*
    dst=${option_params[1]}
    shift 1 option_params
    expr=${option_params}
    req=(dst expr)
    ckreq

    maildircheck "$dst"
    [[ $? = 0 ]] || {
        error "First argument of backup must be a destination maildir"
        return 1
    }
    
    [[ "$expr" = "" ]] && {
        error "No expression set for backup, please indicate what you want to backup"
        act "For example: date:10y..2y (all mails older than 1 year up to 10 years ago)"
        act "Or a simple search string, all expressions can be verified using search."
        return 1
    }
    
    id=`datestamp`.$RANDOM
    c=0

    notice "Backup of mails matched by search expression"
    act "expression: $expr"
    act "destination folder: $dst"

    read_account
    nm_setup

    search ${=expr}

    [[ $DRYRUN = 0 ]] && {
        for i in ${search_results}; do
            refile $i $dst
            [[ $? = 0 ]] || {
                # bail out on every single error
                error "Error refiling emails to destination maildir"
                error "Operation aborted"
                return 1
            }
        done
    }
    return 0
}
