#!/usr/bin/env zsh
#
# Jaro Mail, your humble and faithful electronic postman
#
# a tool to easily and privately handle your e-mail communication
#
# Copyleft (C) 2010-2012 Denis Roio <jaromil@dyne.org>
#
# This source  code is free  software; you can redistribute  it and/or
# modify it under the terms of  the GNU Public License as published by
# the Free  Software Foundation; either  version 3 of the  License, or
# (at your option) any later version.
#
# This source code is distributed in  the hope that it will be useful,
# but  WITHOUT ANY  WARRANTY;  without even  the  implied warranty  of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# Please refer to the GNU Public License for more details.
#
# You should have received a copy of the GNU Public License along with
# this source code; if not, write to:
# Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

VERSION=0.6
DATE=March/2012
JAROMAILEXEC=$0
typeset -a OLDARGS
for arg in ${argv}; do OLDARGS+=($arg); done

##########################
# declare global variables

QUIET=0
DEBUG=1



# which command to use when creating dirs
mkdir="`which mkdir` -m 700 -p"


##########################


PARAM=()
typeset -A global_opts
typeset -A opts

typeset -h name login host protocol port password auth cert

autoload colors; colors

# standard output message routines
# it's always useful to wrap them, in case we change behaviour later
notice() { if [[ $QUIET == 0 ]]; then print "$fg_bold[green][*]$fg_no_bold[white] $1" >&2; fi }
error()  { if [[ $QUIET == 0 ]]; then print "$fg[red][!]$fg[white] $1" >&2; fi }
func()   { if [[ $DEBUG == 1 ]]; then print "$fg[blue][D]$fg[white] $1" >&2; fi }
act()    {
    if [[ $QUIET == 0 ]]; then
	if [ "$1" = "-n" ]; then
	    print -n "$fg_bold[white] . $fg_no_bold[white] $2" >&2;
	else
	    print "$fg_bold[white] . $fg_no_bold[white] $1" >&2;
	fi
    fi
}

# what operating system are we in? use os_detect()
# simplifying modes of operation: GNU or MAC
case $(uname) in
    Linux) OS=GNU
	notice "Jaro Mail v$VERSION running on GNU/Linux"	;;

    Apple) OS=MAC
	notice "Jaro Mail v$VERSION running on Mac/OSX"	;;

    *) OS=GNU # default
	error "Running on an unknown operating system, assuming GNU" ;;
esac


if [ -z $MAILDIRS ]; then 
    MAILDIRS=$HOME/Mail
fi


# default working dir
WORKDIR=$MAILDIRS/jaro

${=mkdir} $MAILDIRS
${=mkdir} $WORKDIR


if [ -r $WORKDIR/Configuration.txt ]; then
    source $WORKDIR/Configuration.txt
fi

# make sure the directory is private
chmod 700 $WORKDIR

# make sure we have a temp and cache dir
${=mkdir} "$WORKDIR/tmp"
${=mkdir} "$WORKDIR/cache"
${=mkdir} "$WORKDIR/log"

PROCMAILDIR=$WORKDIR/.procmail
MUTTDIR=$WORKDIR/.mutt

# make sure tmp is wiped from sensitive data in case of sigINT
TRAPINT() {
	error "Caught signal, aborting operations."
        for f in `ls $WORKDIR/tmp/`; do
	    ${=rm} $f
	done

	if [ "$DEBUG" = "1" ]; then
	    return 1
	else
	    exit 1
	fi
}

# we use pinentry
# comes from gpg project and is secure
# it also conveniently uses the right toolkit
pin_entry() {
    	cat <<EOF | pinentry 2>/dev/null | awk '/^D / { sub(/^D /, ""); print }'
OPTION ttyname=$TTY
OPTION lc-ctype=$LANG
SETTITLE Type your password
SETDESC Type the password for $1 @ $2
SETPROMPT Password:
GETPIN
EOF
}


check_bin() {
    # check for required programs
    for req in pinentry fetchmail procmail; do
	which $req >/dev/null || die "Cannot find $req.  Please install it." 1
    done

    # which wipe command to use
    which wipe > /dev/null && rm="wipe -f -s" \
	|| which srm > /dev/null && rm="srm -f" \
	|| rm="rm -f"
}

# retrieve a password for user @ domain
# put it in variable password
# up to the caller to unset it after use
ask_password() {
    case $OS in
	MAC)
	    func "Looking for password in keyring: $1 @ $2"
	    security find-internet-password -a $1 -s $2 > /dev/null
	    if [ $? != 0 ]; then # its a new password
		password=`pin_entry $1 @ $2`
		act "New password set for $1 @ $2"
		security add-internet-password -a $1 -s $2 -w "${password}"
	    else
		act "Using saved password for $1 @ $2"        
		password=`security find-internet-password -a $1 -s $2 -g \
		    2>&1| awk '/^password:/ { print $2 }' | sed -e 's/"//g'`
	    fi
	    return 0
	    ;;
	GNU)
	    password=`pin_entry $login $host`
	    return 0
	    ;;
	*)
	    error "Unknown system, can't figure out how to handle passwords"
	    return 1
    esac
}

switch_identity() {
    act "switch to identity: $name <$login>"
    rm -f $MUTTDIR/identity
    cat <<EOF > $MUTTDIR/identity
set hostname = $host
set realname = "$name"
set from = "$name <$login>"
EOF
}


option_is_set() {
    #First argument, the option (something like "-s")
    #Second (optional) argument: if it's "out", command will print it out 'set'/'unset'
    #                       This is useful for if conditions
    #Return 0 if is set, 1 otherwise
    [[ -n ${(k)opts[$1]} ]];
    r=$?
    if [[ $2 == out ]]; then
        if [[ $r == 0 ]]; then
            echo 'set'
        else
            echo 'unset'
        fi
    fi
    return $r;
}
option_value() {
    #First argument, the option (something like "-s")
    <<< ${opts[$1]}
}
maildirmake() {

    if [ -z $1 ]; then
	error "internal error: missing argument for maildirmake"
	return
    fi

    if [ -r $1 ]; then
	func "maildir exists: $1"
	return
    fi

    ${=mkdir} ${1}/cur
    ${=mkdir} ${1}/new
    ${=mkdir} ${1}/tmp

}
# arg 1 : account name, es: imap.gmail
read_account() {
    adir=$WORKDIR/Accounts
    acct=$1
    type="`echo $1|cut -d. -f1`"
    # find the file
    if [ -r $adir/$acct.txt ]; then
	acct=$adir/$acct.txt
    elif [ -r $adir/$acct ]; then  # try without .txt
	acct=$adir/$acct
    else
	error "account $acct not found in $adir"
	return 1
    fi
    atmp=$WORKDIR/tmp/$1
    case $type in
	imap|smtp)
	    ttmp=`cat $acct | awk '
    /^#/ { next }
    /^name/ { for(i=2;i<=NF;i++) printf "%s ", $i; printf ";" }
    /^host/ { printf "%s;", $2 }
    /^login/ { printf "%s;", $2 }
    /^transport/ { printf "%s;", $2 }
    /^port/ { printf "%s;", $2 }    
    /^password/ {printf "%s;", $2 }
    /^auth/ { printf "%s;", $2 }
    /^cert/ { printf "%s;", $2 }
    '`
	    name=${ttmp[(ws:;:)1]}
	    host=${ttmp[(ws:;:)2]}
	    login=${ttmp[(ws:;:)3]}
	    transport=${ttmp[(ws:;:)4]}
	    port=${ttmp[(ws:;:)5]}
	    password=${ttmp[(ws:;:)6]}
	    auth=${ttmp[(ws:;:)7]}
	    cert=${ttmp[(ws:;:)8]}

	    # if not present the field is equal to the preceeding one
	    [ "$cert" = "$auth" ] && unset cert
	    [ "$auth" = "$password" ] && unset auth
	    [ "$password" = "$port" ] && unset password

	    func "name: $name"
	    func "host: $host"
	    func "login: $login"
	    func "trans: $transport"
	    func "port: $port"
	    func "cert: $cert"
	    func "auth: $auth"
	    ;;
	*)
	    error "Account type \"$type\" not recognized."
	    return 1
	    ;;
    esac
    return 0
}

queue() {
    local base;
    local tmp;
    local mailfile;
    local msmtpfile;

    # add mails to the sendout queue
    ${=mkdir} $MAILDIRS/outbox
    cd $MAILDIRS/outbox || return 1
    notice "Adding mail to the outbox queue"
    # Create new unique filenames of the form
    # MAILFILE:  ccyy-mm-dd-hh.mm.ss[-x].mail
    # MSMTPFILE: ccyy-mm-dd-hh.mm.ss[-x].msmtp
    # where x is a consecutive number only appended if you send more than one 
    # mail per second.
    base="`date +%Y-%m-%d-%H.%M.%S`"
    func "[$base] queue called with params: ${PARAM[@]}"

    if [ -f "$base.mail" -o -f "$base.msmtp" ]; then
	tmp="$base"
	i=1
	while [ -f "$tmp-$i.mail" -o -f "$tmp-$i.msmtp" ]; do
		i=`expr $i + 1`
	done
	base="$base-$i"
    fi
    mailfile="$base.mail"
    msmtpfile="$base.msmtp"
    # Write command line to $MSMTPFILE
    echo "$@" > "$msmtpfile"
    # Write the mail to $MAILFILE
    cat > "$mailfile"
    cd -
    return 0
}


###########
# FETCHMAIL
fetch() {
    adir=$WORKDIR/Accounts
    acct=$1
    typeset -al all
    if [ -z $acct ]; then # fetch all accounts
	for a in `find $adir -name "imap*"`; do all+=($a); done
	for a in `find $adir -name "pop*"`; do all+=($a); done
    else
	# fetch only one account
	for a in `find $adir -name "$acct*"`; do all+=($a); done
    fi
    if ! [ -r $PROCMAILDIR/rc ]; then
	act "updating procmail configuration"
	update
    fi
    for a in ${all}; do
	read_account `basename $a`
	notice "Fetching mails from $name"
	touch $WORKDIR/tmp/$host.fetch
	chmod 600 $WORKDIR/tmp/$host.fetch
	ask_password $login $host
	if [ $? != 0 ]; then
	    error "Error retrieving password for $login on $host"
	    unset password all
	    return 1
	fi

	cat <<EOF > $WORKDIR/tmp/$host.fetch
poll $host with proto IMAP user "$login" there with password "$password"
keep and ssl warnings 3600 and wants mda "procmail -m $PROCMAILDIR/rc"
antispam 571 550 501 554
EOF
	unset password
    # this function generates a fetchmail configuration and downloads emails
	act "launching fetchmail"
	( sleep 2; act "deleting temporary files"
	    ${=rm} $WORKDIR/tmp/$host.fetch ) &
	fetchmail -f $WORKDIR/tmp/$host.fetch
    done
    return 0
}

######
# SEND
# this function should send all mails in outbox
send() {
    adir=$WORKDIR/Accounts
    acct=$1
    typeset -al all

    # list mails to send
    mailnum=`ls ${MAILDIRS}/outbox | grep 'mail$' | wc -l`
    mailnum=${mailnum// /} # trim whitespace
    if [ "$mailnum" = "0" ]; then
        act "Outbox is empty, no mails to send."
        return 0
    fi

    if [ -z $acct ]; then
	if [ -r $adir/smtp.default ]; then
	    all+=($adir/smtp.default) # use the default account
	else # else will use the first one
	    for a in `find $adir -name "smtp*"`; do all+=($a); done
	fi
    else # or if specified, use a particular account
	for a in `find $adir -name "smtp*$acct*"`; do all+=($a); done
    fi
    read_account `basename ${all[1]}`

    notice "Sending out ${mailnum} mails via `basename ${all[1]}`"
 
    # defaults
    [ -z $auth ] && auth=plain
    [ -z $port ] && port=25
    
    touch $WORKDIR/tmp/$host.send
    chmod 600 $WORKDIR/tmp/$host.send
    ask_password $login $host
    cat <<EOF > $WORKDIR/tmp/$host.send
account default
from ${name}
user ${login}
host ${host}
port ${port}
tls on
tls_starttls on
tls_certcheck off
logfile ${WORKDIR}/log/msmtp.log
auth ${auth}
password ${password}
EOF
    unset password

    for mail in `find $MAILDIRS/outbox -name "*.mail"`; do
       act "`cat ${mail} | grep '^To:'`"
       smtp=`echo ${mail} | sed -e 's/mail/msmtp/'`
       msmtp -C $WORKDIR/tmp/$host.send "`cat ${smtp}`" < "${mail}"
       if [ $? != 0 ]; then
           error "Error sending mail, skipped"
       else
	   act "Mail sent succesfully"
	   ${=rm} ${mail} ${smtp}
       fi
    done
    cd -
    ${=rm} $WORKDIR/tmp/$host.send
    return 0
}

######
# PEEK
# this function will open the MTA to the imap server without fetching mails locally
peek() {
    adir=$WORKDIR/Accounts
    if [ -z $1 ]; then
	error "Peek needs a specific imap account to login."
	act "List of accounts you have configured:"
	for i in `find $adir -name "imap*"`; do act "`basename $i`"; done
	return 1
    fi
    acct=$1
    typeset -al all
    for a in `find $adir -name "imap.$acct*"`; do all+=($a); done
    read_account `basename ${all[1]}`
    notice "Peek into remote imap account $name"
    switch_identity
    case $transport in
	ssl) iproto="imaps" ;;
	plain) iproto="imap" ;;
    esac
    # escape at sign in login
    ilogin=`echo $login | sed 's/@/\\@/'`
    mutt -F $MUTTDIR/rc -f ${iproto}://${ilogin}@${host}
    # TODO automatic input of password in mutt
    return $?
}

update() {
    notice "Updating all configurations and filters"
    # this function should:
    # parse all filters
    # generate procmailrc
    # generate muttrc
    # backup what's too old in the maildirs
    # ...
    
    # debug configuration
    func "MAILDIRS:    $MAILDIRS"
    func "WORKDIR:     $WORKDIR"
    func "MUTTDIR:     $MUTTDIR"
    func "PROCMAILDIR: $PROCMAILDIR"

    # make sure maildirs where to put mails exist
    ${=mkdir} $MAILDIRS
    maildirmake $MAILDIRS/known
    maildirmake $MAILDIRS/sent
    maildirmake $MAILDIRS/priv
    maildirmake $MAILDIRS/postponed
    maildirmake $MAILDIRS/unsorted
    ${=mkdir} $MAILDIRS/outbox
    
    ######
    # MUTT
    ${=mkdir} $MUTTDIR
    rm -f $MUTTDIR/rc
    cat<<EOF > $MUTTDIR/rc
# mutt config generated by Jaro Mail
unset use_domain
set folder = $MAILDIRS
set spoolfile = $MAILDIRS/known/
set record = $MAILDIRS/sent/
set postponed= $MAILDIRS/postponed/
set tmpdir = $WORKDIR/tmp
set query_command = "$WORKDIR/bin/jaro query '%s'"
set sendmail = "$WORKDIR/bin/jaro queue"
set header_cache= $WORKDIR/cache
set maildir_header_cache_verify=no
set editor = "$EDITOR"
set mailcap_path = "$WORKDIR/mailcap"
EOF

    if [ -r $MUTTDIR/general ]; then
	echo "# user tweaked configuration" >> $MUTTDIR/rc
	echo "source ${MUTTDIR}/general" >> $MUTTDIR/rc
    fi

cat <<EOF >> $MUTTDIR/rc
# mailboxes in order of priority
source $MUTTDIR/mboxes

# specific configuration files
# hardcoded path for now (TODO)
source $MUTTDIR/crypto
source $MUTTDIR/colors
source $MUTTDIR/formats
source $MUTTDIR/keybindings
source $MUTTDIR/identity
## end of Jaro Mail generated muttrc
####################################

EOF

    
        # just the header, will be completed later in procmail loop
    rm -f $MUTTDIR/mboxes
    echo -n "mailboxes +priv" > $MUTTDIR/mboxes
    
    ##########
    # PROCMAIL
    ${=mkdir} $PROCMAILDIR
    rm -f $PROCMAILDIR/rc
    touch $PROCMAILDIR/rc
    cat<<EOF >> $PROCMAILDIR/rc
# procmail configuration file generated by Jaro Mail
MAILDIR=$MAILDIRS
DEFAULT=unsorted/
VERBOSE=off
LOGFILE=$WORKDIR/log/procmail.log
SHELL       = /bin/sh       # VERY IMPORTANT
UMASK       = 007           # James Bond :-)
LINEBUF     = 8192          # avoid procmail choke

#  Using Procmail Module Library http://sf.net/projects/pm-lib
PMSRC  = $PROCMAILDIR
#  Load the central initial startup code.
INCLUDERC = \$PMSRC/pm-javar.rc
PF_DEST = ""			# clear these vars
PF_FROM = ""
# don't save multiple copies
PF_RECURSE = yes
:0
* ? test \$PMSRC/pf-chkto.rc
{
EOF

    #######
    echo "# filters generated from Accounts" >> $PROCMAILDIR/rc
    typeset -al accts
    for f in `cat $WORKDIR/Accounts/* | awk '/^login/ { print $2 }'`; do
	echo "ADDR=${f}\tDEST=priv\tINCLUDERC=\$PMSRC/pf-chkto.rc"  >> $PROCMAILDIR/rc
    done

    #######
    echo "# filters generated from Filters.txt" >> $PROCMAILDIR/rc
    
    for f in `cat $WORKDIR/Filters.txt | awk '/^#/ {next} /^./ { print $1 ";" $2 ";" $3 ";" $4 }'`; do
	header="${f[(ws:;:)1]}"
	address="${f[(ws:;:)2]}"
	action="${f[(ws:;:)3]}"
	destination="${f[(ws:;:)4]}"
	case $header in
	    to)
		print "ADDR=${address}\tDEST=${destination}\tINCLUDERC=\$PMSRC/pf-chkto.rc" \
		    >> $PROCMAILDIR/rc
		;;
	    from)
		print "ADDR=${address}\tDEST=${destination}\tINCLUDERC=\$PMSRC/pf-check.rc" \
		    >> $PROCMAILDIR/rc
		;;
	    *)
		error "unsupported filter: $header (skipped)"
		;;
	esac
	# MUTT (generate mailboxes priority this parser)
	echo  " \\" >> $MUTTDIR/mboxes
	echo -n " +${destination} " >> $MUTTDIR/mboxes
    done

    echo " \\" >> $MUTTDIR/mboxes
    echo " +unsorted" >> $MUTTDIR/mboxes
    uniq $MUTTDIR/mboxes > $WORKDIR/tmp/mboxes
    mv $WORKDIR/tmp/mboxes $MUTTDIR/mboxes
    rm -f $WORKDIR/tmp/mboxes

    cat <<EOF >> $PROCMAILDIR/rc
}

# save the mails
:0
* PF_DEST ?? .
* ? test \$PMSRC/pf-save.rc
{ INCLUDERC=\$PMSRC/pf-save.rc }

# if the sender is known (ldbd recognizes it) then put mail in high priority 'known'
:0 w:
* ? formail -x"From:" | head -n1 | tr 'A-Z' 'a-z' | sed 's/.*\W\([0-9a-z_.-]\+@[0-9a-z_.-]\+\).*/\1/' | xargs jaro query
known/

# if got here, go to unsorted

# save the mails
:0
* PF_DEST ?? .
* ? test \$PMSRC/pf-save.rc
{ INCLUDERC=\$PMSRC/pf-save.rc }

EOF
    return 0
}

usage() {
    cat <<EOF
Jaro Mail $VERSION - your humble and faithful electronic postman

 Copyright (C) 2010-2012 Dyne.org Foundation, License GNU GPL v3+
 This is free software: you are free to change and redistribute it
 The latest Tomb sourcecode is published on <http://tomb.dyne.org>

Syntact: jaro command [options] [account]

Commands:

 queue
 send
 peek
 fetch
 sync

Options:

 -h     print this help
 -v     version information for this tool
 -q     run quietly without printing informations
 -D     print debugging information at runtime


For more informations on Jaro Mail read the manual: man jaro
Please report bugs on <http://bugs.dyne.org>.
EOF
}


main()
    {
    local -A subcommands_opts
    ### Options configuration
    #Hi, dear developer! Are you trying to add a new subcommand, or to add some options?
    #Well, keep in mind that:
    # 1. An option CAN'T have differente meanings/behaviour in different subcommands.
    #    For example, "-s" means "size" and accept an argument. If you are tempted to add
    #    an option "-s" (that means, for example "silent", and doesn't accept an argument)
    #              DON'T DO IT!
    #     There are two reasons for that:
    #       I. usability; user expect that "-s" is "size
    #       II. Option parsing WILL EXPLODE if you do this kind of bad things
    #               (it will say "option defined more than once, and he's right)
    main_opts=(q -quiet=q D -debug=D h -help=h v -version=v n -dry-run=n)
    subcommands_opts[__default]=""
    subcommands_opts[queue]=""
    subcommands_opts[fetch]=""
    subcommands_opts[send]=""
    subcommands_opts[read]=""
    subcommands_opts[compose]=""
    subcommands_opts[peek]=""    
    subcommands_opts[update]=""
    subcommands_opts[query]=""
    subcommands_opts[source]=""
#    subcommands_opts[mount]=${subcommands_opts[open]}
#    subcommands_opts[create]="s: -size=s -ignore-swap k: -key=k"
    ### Detect subcommand
    local -aU every_opts #every_opts behave like a set; that is, an array with unique elements
    for optspec in $subcommands_opts$main_opts; do
        for opt in ${=optspec}; do
            every_opts+=${opt}
        done
    done
    local -a oldstar
    oldstar=($argv)
    zparseopts -M -E -D -Adiscardme ${every_opts}
    unset discardme
    subcommand=$1
    if [[ -z $subcommand ]]; then
        subcommand="__default"
    fi
    if [[ -z ${(k)subcommands_opts[$subcommand]} ]]; then #there's no such subcommand
        error "Subcommand '$subcommand' doesn't exist"
        exit 127
    fi
    argv=(${oldstar})
    unset oldstar

    ### Parsing global + command-specific options
    # zsh magic: ${=string} will split to multiple arguments when spaces occur
    set -A cmd_opts ${main_opts} ${=subcommands_opts[$subcommand]}
    if [[ -n $cmd_opts ]]; then #if there is no option, we don't need parsing
        zparseopts -M -E -D -Aopts ${cmd_opts}
	if [[ $? != 0 ]]; then
	    error "Some error occurred during option processing."
	    exit 127
	fi
    fi
  #build PARAM (array of arguments) and check if there are unrecognized options
    local ok=0
#    PARAM=()
    for arg in $*; do
	if [[ $arg == '--' || $arg == '-' ]]; then
	    ok=1
	    continue #it shouldnt be appended to PARAM
	elif [[ $arg[1] == '-'  ]]; then
	    if [[ $ok == 0 ]]; then
		error "unrecognized option $arg"
		exit 127
	    fi
	fi
	PARAM+=$arg
    done
  #first parameter actually is the subcommand: delete it and shift
    if [[ $subcommand != '__default' ]]; then
	PARAM[1]=()
	shift
    fi
  ### End parsing command-specific options

    if option_is_set -v; then act "Jaro Mail - $VERSION"; fi
    if option_is_set -h; then usage;  fi
    if option_is_set -q; then QUIET=1; fi
    if option_is_set -D; then func "Debug messages ON"; DEBUG=1; fi
        
    case "$subcommand" in
	queue) queue ${PARAM} ;;
	fetch) fetch ${PARAM} ;;
	send) send ${PARAM} ;;
	peek) peek ${PARAM} ;;
	read) mutt -F $MUTTDIR/rc ;;
	compose) mutt -F $MUTTDIR/rc ${PARAM} ;;
	update) update ;;
	query) ${WORKDIR}/.lbdb/lbdbq ${PARAM} ;;
	'source')   return 0 ;;
	__default) ;;
	*) error "command \"$subcommand\" not recognized"
	    act "try -h for help"
	    return 1
	    ;;
    esac
    return 0
}

check_bin
main $@
